const countries = {
	'Türkiye': 'TR',
	Afganistan: 'AF',
	Almanya: 'DE',
	'Amerika Birleşik Devletleri': 'US',
	'Amerikan Samoası': 'AS',
	Andora: 'AD',
	Angola: 'AO',
	Arjantin: 'AR',
	Arnavutluk: 'AL',
	Aruba: 'AW',
	Avustralya: 'AU',
	Avusturya: 'AT',
	Azerbaycan: 'AZ',
	Bahamalar: 'BS',
	Bahreyn: 'BH',
	'Bangladeş': 'BD',
	Barbados: 'BB',
	'Batı Sahara': 'EH',
	Belize: 'BZ',
	'Belçika': 'BE',
	Benin: 'BJ',
	Bermuda: 'BM',
	'Beyaz Rusya': 'BY',
	Bhutan: 'BT',
	'Birleşik Arap Emirlikleri': 'AE',
	'Birleşik Krallık': 'GB',
	Bolivya: 'BO',
	'Bosna Hersek': 'BA',
	Botsvana: 'BW',
	'Bouvet Adası': 'BV',
	Brezilya: 'BR',
	Brunei: 'BN',
	Bulgaristan: 'BG',
	'Burkina Faso': 'BF',
	Burundi: 'BI',
	Cezayir: 'DZ',
	Cibuti: 'DJ',
	'Çad': 'TD',
	'Çek Cumhuriyeti': 'CZ',
	'Çin': 'CN',
	Danimarka: 'DK',
	Dominik: 'DM',
	'Dominik Cumhuriyeti': 'DO',
	Ekvator: 'EC',
	'Ekvator Ginesi': 'GQ',
	'El Salvador': 'SV',
	Endonezya: 'ID',
	Eritre: 'ER',
	Ermenistan: 'AM',
	Estonya: 'EE',
	Etiyopya: 'ET',
	'Falkland Adaları (Malvinalar)': 'FK',
	'Faroe Adaları': 'FO',
	Fas: 'MA',
	Fiji: 'FJ',
	'Fildişi Sahilleri': 'CI',
	Filipinler: 'PH',
	'Filistin Bölgesi': 'PS',
	Finlandiya: 'FI',
	Fransa: 'FR',
	Gabon: 'GA',
	Gambia: 'GM',
	Gana: 'GH',
	Gine: 'GN',
	'Gine-Bissau': 'GW',
	Granada: 'GD',
	'Grönland': 'GL',
	Guadeloupe: 'GP',
	Guam: 'GU',
	Guatemala: 'GT',
	Guernsey: 'GG',
	Guyana: 'GY',
	'Güney Afrika': 'ZA',
	'Güney Georgia ve Güney Sandwich Adaları': 'GS',
	'Güney Kore': 'KR',
	'Güney Kıbrıs Rum Kesimi': 'CY',
	'Gürcistan': 'GE',
	Haiti: 'HT',
	'Heard Adası ve McDonald Adaları': 'HM',
	Hindistan: 'IN',
	'Hint Okyanusu İngiliz Bölgesi': 'IO',
	Hollanda: 'NL',
	'Hollanda Antilleri': 'AN',
	Honduras: 'HN',
	'Hong Kong SAR - Çin': 'HK',
	'Hırvatistan': 'HR',
	Irak: 'IQ',
	'İran': 'IR',
	'İrlanda': 'IE',
	'İspanya': 'ES',
	'İsrail': 'IL',
	'İsveç': 'SE',
	'İsviçre': 'CH',
	'İtalya': 'IT',
	'İzlanda': 'IS',
	Jamaika: 'JM',
	Japonya: 'JP',
	'Kamboçya': 'KH',
	Kamerun: 'CM',
	Kanada: 'CA',
	'Karadağ': 'ME',
	Katar: 'QA',
	'Kayman Adaları': 'KY',
	Kazakistan: 'KZ',
	Kenya: 'KE',
	Kiribati: 'KI',
	Kolombiya: 'CO',
	Komorlar: 'KM',
	Kongo: 'CG',
	'Kongo Demokratik Cumhuriyeti': 'CD',
	'Kosta Rika': 'CR',
	Kuveyt: 'KW',
	'Kuzey Kore': 'KP',
	'Küba': 'CU',
	'Kırgızistan': 'KG',
	Laos: 'LA',
	Lesotho: 'LS',
	Letonya: 'LV',
	Liberya: 'LR',
	Libya: 'LY',
	Liechtenstein: 'LI',
	Litvanya: 'LT',
	'Lübnan': 'LB',
	'Lüksemburg': 'LU',
	Macaristan: 'HU',
	Madagaskar: 'MG',
	'Makao S.A.R. Çin': 'MO',
	Makedonya: 'MK',
	Malavi: 'MW',
	Maldivler: 'MV',
	Malezya: 'MY',
	Mali: 'ML',
	Malta: 'MT',
	'Man Adası': 'IM',
	Mauritius: 'MU',
	Meksika: 'MX',
	'Mikronezya Federal Eyaletleri': 'FM',
	'Moldovya Cumhuriyeti': 'MD',
	Moritanya: 'MR',
	Mozambik: 'MZ',
	'Moğolistan': 'MN',
	Myanmar: 'MM',
	'Mısır': 'EG',
	Namibya: 'NA',
	Nauru: 'NR',
	Nepal: 'NP',
	Nijer: 'NE',
	Nijerya: 'NG',
	Nikaragua: 'NI',
	'Norveç': 'NO',
	'Orta Afrika Cumhuriyeti': 'CF',
	'Özbekistan': 'UZ',
	Pakistan: 'PK',
	Panama: 'PA',
	'Papua Yeni Gine': 'PG',
	Paraguay: 'PY',
	Peru: 'PE',
	Polonya: 'PL',
	Portekiz: 'PT',
	'Porto Riko': 'PR',
	Romanya: 'RO',
	Ruanda: 'RW',
	'Rusya Federasyonu': 'RU',
	Samoa: 'WS',
	'San Marino': 'SM',
	Senegal: 'SN',
	'Sierra Leone': 'SL',
	Singapur: 'SG',
	Slovakya: 'SK',
	Slovenya: 'SI',
	'Solomon Adaları': 'SB',
	Somali: 'SO',
	'Sri Lanka': 'LK',
	Sudan: 'SD',
	Surinam: 'SR',
	Suriye: 'SY',
	'Suudi Arabistan': 'SA',
	Svaziland: 'SZ',
	'Sırbistan': 'RS',
	'Sırbistan-Karadağ': 'CS',
	'Şili': 'CL',
	Tacikistan: 'TJ',
	Tanzanya: 'TZ',
	Tayland: 'TH',
	Tayvan: 'TW',
	Togo: 'TG',
	Tonga: 'TO',
	'Trinidad ve Tobago': 'TT',
	Tunus: 'TN',
	'Turks ve Caicos Adaları': 'TC',
	Tuvalu: 'TV',
	'Türkmenistan': 'TM',
	Uganda: 'UG',
	Ukrayna: 'UA',
	Umman: 'OM',
	Uruguay: 'UY',
	'Ürdün': 'JO',
	Vatikan: 'VA',
	Venezuela: 'VE',
	Vietnam: 'VN',
	Yemen: 'YE',
	'Yeni Zelanda': 'NZ',
	Yunanistan: 'GR',
	Zambiya: 'ZM',
	Zimbabve: 'ZW'
  };



export default countries;