const countries = {
	'Türkiye': 'TR',
	Afganistan: 'AF',
	Almanya: 'DE',
	'Amerika Birleşik Devletleri': 'US',
	'Amerikan Samoası': 'AS',
	Andora: 'AD',
	Angola: 'AO',
	Arjantin: 'AR',
	Arnavutluk: 'AL',
	Aruba: 'AW',
	Avustralya: 'AU',
	Avusturya: 'AT',
	Azerbaycan: 'AZ',
	Bahamalar: 'BS',
	Bahreyn: 'BH',
	'Bangladeş': 'BD',
	Barbados: 'BB',
	'Batı Sahara': 'EH',
	Belize: 'BZ',
	'Belçika': 'BE',
	Benin: 'BJ',
	Bermuda: 'BM',
	'Beyaz Rusya': 'BY',
	Bhutan: 'BT',
	'Birleşik Arap Emirlikleri': 'AE',
	'Birleşik Krallık': 'GB',
	Bolivya: 'BO',
	'Bosna Hersek': 'BA',
	Botsvana: 'BW',
	'Bouvet Adası': 'BV',
	Brezilya: 'BR',
	Brunei: 'BN',
	Bulgaristan: 'BG',
	'Burkina Faso': 'BF',
	Burundi: 'BI',
	Cezayir: 'DZ',
	Cibuti: 'DJ',
	'Çad': 'TD',
	'Çek Cumhuriyeti': 'CZ',
	'Çin': 'CN',
	Danimarka: 'DK',
	Dominik: 'DM',
	'Dominik Cumhuriyeti': 'DO',
	Ekvator: 'EC',
	'Ekvator Ginesi': 'GQ',
	'El Salvador': 'SV',
	Endonezya: 'ID',
	Eritre: 'ER',
	Ermenistan: 'AM',
	Estonya: 'EE',
	Etiyopya: 'ET',
	'Falkland Adaları (Malvinalar)': 'FK',
	'Faroe Adaları': 'FO',
	Fas: 'MA',
	Fiji: 'FJ',
	'Fildişi Sahilleri': 'CI',
	Filipinler: 'PH',
	'Filistin Bölgesi': 'PS',
	Finlandiya: 'FI',
	Fransa: 'FR',
	Gabon: 'GA',
	Gambia: 'GM',
	Gana: 'GH',
	Gine: 'GN',
	'Gine-Bissau': 'GW',
	Granada: 'GD',
	'Grönland': 'GL',
	Guadeloupe: 'GP',
	Guam: 'GU',
	Guatemala: 'GT',
	Guernsey: 'GG',
	Guyana: 'GY',
	'Güney Afrika': 'ZA',
	'Güney Georgia ve Güney Sandwich Adaları': 'GS',
	'Güney Kore': 'KR',
	'Güney Kıbrıs Rum Kesimi': 'CY',
	'Gürcistan': 'GE',
	Haiti: 'HT',
	'Heard Adası ve McDonald Adaları': 'HM',
	Hindistan: 'IN',
	'Hint Okyanusu İngiliz Bölgesi': 'IO',
	Hollanda: 'NL',
	'Hollanda Antilleri': 'AN',
	Honduras: 'HN',
	'Hong Kong SAR - Çin': 'HK',
	'Hırvatistan': 'HR',
	Irak: 'IQ',
	'İran': 'IR',
	'İrlanda': 'IE',
	'İspanya': 'ES',
	'İsrail': 'IL',
	'İsveç': 'SE',
	'İsviçre': 'CH',
	'İtalya': 'IT',
	'İzlanda': 'IS',
	Jamaika: 'JM',
	Japonya: 'JP',
	'Kamboçya': 'KH',
	Kamerun: 'CM',
	Kanada: 'CA',
	'Karadağ': 'ME',
	Katar: 'QA',
	'Kayman Adaları': 'KY',
	Kazakistan: 'KZ',
	Kenya: 'KE',
	Kiribati: 'KI',
	Kolombiya: 'CO',
	Komorlar: 'KM',
	Kongo: 'CG',
	'Kongo Demokratik Cumhuriyeti': 'CD',
	'Kosta Rika': 'CR',
	Kuveyt: 'KW',
	'Kuzey Kore': 'KP',
	'Küba': 'CU',
	'Kırgızistan': 'KG',
	Laos: 'LA',
	Lesotho: 'LS',
	Letonya: 'LV',
	Liberya: 'LR',
	Libya: 'LY',
	Liechtenstein: 'LI',
	Litvanya: 'LT',
	'Lübnan': 'LB',
	'Lüksemburg': 'LU',
	Macaristan: 'HU',
	Madagaskar: 'MG',
	'Makao S.A.R. Çin': 'MO',
	Makedonya: 'MK',
	Malavi: 'MW',
	Maldivler: 'MV',
	Malezya: 'MY',
	Mali: 'ML',
	Malta: 'MT',
	'Man Adası': 'IM',
	Mauritius: 'MU',
	Meksika: 'MX',
	'Mikronezya Federal Eyaletleri': 'FM',
	'Moldovya Cumhuriyeti': 'MD',
	Moritanya: 'MR',
	Mozambik: 'MZ',
	'Moğolistan': 'MN',
	Myanmar: 'MM',
	'Mısır': 'EG',
	Namibya: 'NA',
	Nauru: 'NR',
	Nepal: 'NP',
	Nijer: 'NE',
	Nijerya: 'NG',
	Nikaragua: 'NI',
	'Norveç': 'NO',
	'Orta Afrika Cumhuriyeti': 'CF',
	'Özbekistan': 'UZ',
	Pakistan: 'PK',
	Panama: 'PA',
	'Papua Yeni Gine': 'PG',
	Paraguay: 'PY',
	Peru: 'PE',
	Polonya: 'PL',
	Portekiz: 'PT',
	'Porto Riko': 'PR',
	Romanya: 'RO',
	Ruanda: 'RW',
	'Rusya Federasyonu': 'RU',
	Samoa: 'WS',
	'San Marino': 'SM',
	Senegal: 'SN',
	'Sierra Leone': 'SL',
	Singapur: 'SG',
	Slovakya: 'SK',
	Slovenya: 'SI',
	'Solomon Adaları': 'SB',
	Somali: 'SO',
	'Sri Lanka': 'LK',
	Sudan: 'SD',
	Surinam: 'SR',
	Suriye: 'SY',
	'Suudi Arabistan': 'SA',
	Svaziland: 'SZ',
	'Sırbistan': 'RS',
	'Sırbistan-Karadağ': 'CS',
	'Şili': 'CL',
	Tacikistan: 'TJ',
	Tanzanya: 'TZ',
	Tayland: 'TH',
	Tayvan: 'TW',
	Togo: 'TG',
	Tonga: 'TO',
	'Trinidad ve Tobago': 'TT',
	Tunus: 'TN',
	'Turks ve Caicos Adaları': 'TC',
	Tuvalu: 'TV',
	'Türkmenistan': 'TM',
	Uganda: 'UG',
	Ukrayna: 'UA',
	Umman: 'OM',
	Uruguay: 'UY',
	'Ürdün': 'JO',
	Vatikan: 'VA',
	Venezuela: 'VE',
	Vietnam: 'VN',
	Yemen: 'YE',
	'Yeni Zelanda': 'NZ',
	Yunanistan: 'GR',
	Zambiya: 'ZM',
	Zimbabve: 'ZW'
  };

  export const codes = {
    AF: 'Afghanistan',  
    AX: 'Aland Islands',
    AL: 'Albania',      
    DZ: 'Algeria',
    AS: 'American Samoa',
    AD: 'Andorra',
    AO: 'Angola',
    AI: 'Anguilla',
    AQ: 'Antarctica',
    AG: 'Antigua and Barbuda',
    AR: 'Argentina',
    AM: 'Armenia',
    AW: 'Aruba',
    AU: 'Australia',
    AT: 'Austria',
    AZ: 'Azerbaijan',
    BS: 'Bahamas',
    BH: 'Bahrain',
    BD: 'Bangladesh',
    BB: 'Barbados',
    BY: 'Belarus',
    BE: 'Belgium',
    BZ: 'Belize',
    BJ: 'Benin',
    BM: 'Bermuda',
    BT: 'Bhutan',
    BO: 'Bolivia',
    BQ: 'Bonaire, Saint Eustatius and Saba ',
    BA: 'Bosnia and Herzegovina',
    BW: 'Botswana',
    BV: 'Bouvet Island',
    BR: 'Brazil',
    IO: 'British Indian Ocean Territory',
    VG: 'British Virgin Islands',
    BN: 'Brunei',
    BG: 'Bulgaria',
    BF: 'Burkina Faso',
    BI: 'Burundi',
    KH: 'Cambodia',
    CM: 'Cameroon',
    CA: 'Canada',
    CV: 'Cape Verde',
    KY: 'Cayman Islands',
    CF: 'Central African Republic',
    TD: 'Chad',
    CL: 'Chile',
    CN: 'China',
    CX: 'Christmas Island',
    CC: 'Cocos Islands',
    CO: 'Colombia',
    KM: 'Comoros',
    CK: 'Cook Islands',
    CR: 'Costa Rica',
    HR: 'Croatia',
    CU: 'Cuba',
    CW: 'Curacao',
    CY: 'Cyprus',
    CZ: 'Czechia',
    CD: 'Democratic Republic of the Congo',
    DK: 'Denmark',
    DJ: 'Djibouti',
    DM: 'Dominica',
    DO: 'Dominican Republic',
    TL: 'East Timor',
    EC: 'Ecuador',
    EG: 'Egypt',
    SV: 'El Salvador',
    GQ: 'Equatorial Guinea',
    ER: 'Eritrea',
    EE: 'Estonia',
    ET: 'Ethiopia',
    FK: 'Falkland Islands',
    FO: 'Faroe Islands',
    FJ: 'Fiji',
    FI: 'Finland',
    FR: 'France',
    GF: 'French Guiana',
    PF: 'French Polynesia',
    TF: 'French Southern Territories',
    GA: 'Gabon',
    GM: 'Gambia',
    GE: 'Georgia',
    DE: 'Germany',
    GH: 'Ghana',
    GI: 'Gibraltar',
    GR: 'Greece',
    GL: 'Greenland',
    GD: 'Grenada',
    GP: 'Guadeloupe',
    GU: 'Guam',
    GT: 'Guatemala',
    GG: 'Guernsey',
    GW: 'Guinea-Bissau',
    GN: 'Guinea',
    GY: 'Guyana',
    HT: 'Haiti',
    HM: 'Heard Island and McDonald Islands',
    HN: 'Honduras',
    HK: 'Hong Kong',
    HU: 'Hungary',
    IS: 'Iceland',
    IN: 'India',
    ID: 'Indonesia',
    IR: 'Iran',
    IQ: 'Iraq',
    IE: 'Ireland',
    IM: 'Isle of Man',
    IL: 'Israel',
    IT: 'Italy',
    CI: 'Ivory Coast',
    JM: 'Jamaica',
    JP: 'Japan',
    JE: 'Jersey',
    JO: 'Jordan',
    KZ: 'Kazakhstan',
    KE: 'Kenya',
    KI: 'Kiribati',
    XK: 'Kosovo',
    KW: 'Kuwait',
    KG: 'Kyrgyzstan',
    LA: 'Laos',
    LV: 'Latvia',
    LB: 'Lebanon',
    LS: 'Lesotho',
    LR: 'Liberia',
    LY: 'Libya',
    LI: 'Liechtenstein',
    LT: 'Lithuania',
    LU: 'Luxembourg',
    MO: 'Macao',
    MK: 'Macedonia',
    MG: 'Madagascar',
    MW: 'Malawi',
    MY: 'Malaysia',
    MV: 'Maldives',
    ML: 'Mali',
    MT: 'Malta',
    MH: 'Marshall Islands',
    MQ: 'Martinique',
    MR: 'Mauritania',
    MU: 'Mauritius',
    YT: 'Mayotte',
    MX: 'Mexico',
    FM: 'Micronesia',
    MD: 'Moldova',
    MC: 'Monaco',
    MN: 'Mongolia',
    ME: 'Montenegro',
    MS: 'Montserrat',
    MA: 'Morocco',
    MZ: 'Mozambique',
    MM: 'Myanmar',
    NA: 'Namibia',
    NR: 'Nauru',
    NP: 'Nepal',
    NL: 'Netherlands',
    NC: 'New Caledonia',
    NZ: 'New Zealand',
    NI: 'Nicaragua',
    NE: 'Niger',
    NG: 'Nigeria',
    NU: 'Niue',
    NF: 'Norfolk Island',
    KP: 'North Korea',
    MP: 'Northern Mariana Islands',
    NO: 'Norway',
    OM: 'Oman',
    PK: 'Pakistan',
    PW: 'Palau',
    PS: 'Palestinian Territory',
    PA: 'Panama',
    PG: 'Papua New Guinea',
    PY: 'Paraguay',
    PE: 'Peru',
    PH: 'Philippines',
    PN: 'Pitcairn',
    PL: 'Poland',
    PT: 'Portugal',
    PR: 'Puerto Rico',
    QA: 'Qatar',
    CG: 'Republic of the Congo',
    RE: 'Reunion',
    RO: 'Romania',
    RU: 'Russia',
    RW: 'Rwanda',
    BL: 'Saint Barthelemy',
    SH: 'Saint Helena',
    KN: 'Saint Kitts and Nevis',
    LC: 'Saint Lucia',
    MF: 'Saint Martin',
    PM: 'Saint Pierre and Miquelon',
    VC: 'Saint Vincent and the Grenadines',
    WS: 'Samoa',
    SM: 'San Marino',
    ST: 'Sao Tome and Principe',
    SA: 'Saudi Arabia',
    SN: 'Senegal',
    RS: 'Serbia',
    SC: 'Seychelles',
    SL: 'Sierra Leone',
    SG: 'Singapore',
    SX: 'Sint Maarten',
    SK: 'Slovakia',
    SI: 'Slovenia',
    SB: 'Solomon Islands',
    SO: 'Somalia',
    ZA: 'South Africa',
    GS: 'South Georgia and the South Sandwich Islands',
    KR: 'Korea, South',
    SS: 'South Sudan',
    ES: 'Spain',
    LK: 'Sri Lanka',
    SD: 'Sudan',
    SR: 'Suriname',
    SJ: 'Svalbard and Jan Mayen',
    SZ: 'Swaziland',
    SE: 'Sweden',
    CH: 'Switzerland',
    SY: 'Syria',
    TW: 'Taiwan*',
    TJ: 'Tajikistan',
    TZ: 'Tanzania',
    TH: 'Thailand',
    TG: 'Togo',
    TK: 'Tokelau',
    TO: 'Tonga',
    TT: 'Trinidad and Tobago',
    TN: 'Tunisia',
    TR: 'Turkey',
    TM: 'Turkmenistan',
    TC: 'Turks and Caicos Islands',
    TV: 'Tuvalu',
    VI: 'U.S. Virgin Islands',
    UG: 'Uganda',
    UA: 'Ukraine',
    AE: 'United Arab Emirates',
    GB: 'United Kingdom',
    UY: 'Uruguay',
    US: 'US',
    UZ: 'Uzbekistan',
    VU: 'Vanuatu',
    VA: 'Vatican',
    VE: 'Venezuela',
    VN: 'Vietnam',
    WF: 'Wallis and Futuna',
    EH: 'Western Sahara',
    YE: 'Yemen',
    ZM: 'Zambia',
    ZW: 'Zimbabwe'
  };

export default countries;